spring:
  application:
    name: devicemanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/devices
    username: devices
    password: devices
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true